/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-12-28 05:22:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("Author: W3layouts\r\n");
      out.write("Author URL: http://w3layouts.com\r\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\r\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\r\n");
      out.write("-->\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("	<title>Home Loan a Banking Category Flat Bootstrap Responsive Website Template | About :: w3layouts</title>\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<meta name=\"keywords\" content=\"Home Loan Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("	<script>\r\n");
      out.write("		addEventListener(\"load\", function () {\r\n");
      out.write("			setTimeout(hideURLbar, 0);\r\n");
      out.write("		}, false);\r\n");
      out.write("\r\n");
      out.write("		function hideURLbar() {\r\n");
      out.write("			window.scrollTo(0, 1);\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Bootstrap Core CSS -->\r\n");
      out.write("	<link href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/bootstrap.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("	<link href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/style.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("	<!-- font-awesome icons -->\r\n");
      out.write("	<link href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/fontawesome-all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("	<!-- //Custom Theme files -->\r\n");
      out.write("	<!-- online fonts -->\r\n");
      out.write("	<!-- titles -->\r\n");
      out.write("	<link href=\"//fonts.googleapis.com/css?family=Raleway:300,400,500,600,700,800,900\" rel=\"stylesheet\">\r\n");
      out.write("	<!-- body -->\r\n");
      out.write("	<link href=\"//fonts.googleapis.com/css?family=Poppins:400,500,600,700,800\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	<!-- header -->\r\n");
      out.write("	<header>\r\n");
      out.write("	<div class=\"top\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"t-op row\">\r\n");
      out.write("					<div class=\"col-sm-6 top-middle\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a></li>\r\n");
      out.write("							<li><a href=\"#\"><i class=\"fab fa-twitter\"></i></a></li>\r\n");
      out.write("							<li><a href=\"#\"><i class=\"fab fa-google-plus-g\"></i></a></li>\r\n");
      out.write("							<li><a href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-sm-6 top-left\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><i class=\"fas fa-phone\"></i> +021 365 777</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("				<h1>\r\n");
      out.write("					<a class=\"navbar-brand text-capitalize\" href=index>\r\n");
      out.write("						Home Loan\r\n");
      out.write("					</a>\r\n");
      out.write("				</h1>\r\n");
      out.write("				<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\"\r\n");
      out.write("				    aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("					<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("				</button>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("					<ul class=\"navbar-nav text-center  ml-lg-auto\">\r\n");
      out.write("						<li class=\"nav-item mr-3\">\r\n");
      out.write("							<a class=\"nav-link\" href=index>Home\r\n");
      out.write("								<span class=\"sr-only\">(current)</span>\r\n");
      out.write("							</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"nav-item  active mr-3\">\r\n");
      out.write("							<a class=\"nav-link\" href=\"about\">About</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"nav-item  mr-3\">\r\n");
      out.write("							<a class=\"nav-link\" href=\"services\">Services</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"nav-item dropdown mr-3\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("							    aria-expanded=\"false\">\r\n");
      out.write("								Dropdown\r\n");
      out.write("							</a>\r\n");
      out.write("							<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"typography\">Typography</a>\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"gallery\">Gallery</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<!-- <li class=\"nav-item\">\r\n");
      out.write("							<a class=\"nav-link\" href=\"contact\">contact</a>\r\n");
      out.write("						</li> -->\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- //header -->\r\n");
      out.write("	<!-- banner -->\r\n");
      out.write("	<section class=\"banner-1\">\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- //banner -->\r\n");
      out.write("	<!-- about -->\r\n");
      out.write("	<section class=\"welcome py-5\">\r\n");
      out.write("		<div class=\"container py-md-4 mt-md-3\">\r\n");
      out.write("			<h2 class=\"heading-agileinfo\">About Us <span>Speed Up the Loan Process</span></h2>\r\n");
      out.write("			<span class=\"w3-line black\"></span>\r\n");
      out.write("			<div class=\"row about-tp mt-md-5 pt-5\">\r\n");
      out.write("				<div class=\"col-lg-6 welcome-left\">\r\n");
      out.write("					<h3>Welcome</h3>\r\n");
      out.write("					<h4>We are committed to offering travel services of the highest quality, combining our energy and enthusiasm, with our years\r\n");
      out.write("						of experience. Our greatest satisfaction comes in serving large numbers of satisfied clients who have experienced the\r\n");
      out.write("						joys and inspiration of travel.</h4>\r\n");
      out.write("					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse porta erat sit amet eros sagittis, quis hendrerit\r\n");
      out.write("						libero aliquam. Fusce semper augue ac dolor efficitur, a pretium metus pellentesque.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-6 welcome-right\">\r\n");
      out.write("					<div class=\"welcome-right-top\">\r\n");
      out.write("						<img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/g1.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- //about -->\r\n");
      out.write("	<!-- w3layouts_bottom -->\r\n");
      out.write("<section class=\"w3layouts_bottom\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-lg-9 w3layouts_getin_info\">\r\n");
      out.write("				<h3>Donât Miss Your Perfect House!</h3>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-lg-3 w3layouts_getin\">\r\n");
      out.write("				<a href=\"contact\">Contact Us</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("<!-- //w3layouts_bottom -->\r\n");
      out.write("\r\n");
      out.write("	<!-- about-team -->\r\n");
      out.write("	<section class=\"team py-5\">\r\n");
      out.write("		<div class=\"container py-md-4 mt-md-3\">\r\n");
      out.write("			<h3 class=\"heading-agileinfo\">Our Team <span>Speed Up the Loan Process</span></h3>\r\n");
      out.write("			<span class=\"w3-line black\"></span>\r\n");
      out.write("			<div class=\"row team-row-agileinfo mt-md-5 pt-5\">\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-sm-6 team-grids\">\r\n");
      out.write("					<div class=\"thumbnail team-agileits\">\r\n");
      out.write("						<img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/te1.jpg\" class=\"img-fluid\" alt=\"\" />\r\n");
      out.write("						<div class=\"effectd-caption\">\r\n");
      out.write("							<h4 class=\"mb-3\">Vaura Tegsner</h4>\r\n");
      out.write("							<div class=\"social-lsicon\">\r\n");
      out.write("								<a href=\"#\" class=\"social-button twitter\">\r\n");
      out.write("									<span class=\"fab fa-twitter\"></span>\r\n");
      out.write("								</a>\r\n");
      out.write("								<a href=\"#\" class=\"social-button facebook\">\r\n");
      out.write("									<span class=\"fab fa-facebook-f\"></span>\r\n");
      out.write("								</a>\r\n");
      out.write("								<a href=\"#\" class=\"social-button google\">\r\n");
      out.write("									<span class=\"fab fa-google-plus-g\"></span>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-sm-6 team-grids\">\r\n");
      out.write("					<div class=\"thumbnail team-agileits\">\r\n");
      out.write("						<img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/te2.jpg\" class=\"img-fluid\" alt=\"\" />\r\n");
      out.write("						<div class=\"effectd-caption\">\r\n");
      out.write("							<h4 class=\"mb-3\">Jessika John</h4>\r\n");
      out.write("							<div class=\"social-lsicon\">\r\n");
      out.write("								<a href=\"#\" class=\"social-button twitter\">\r\n");
      out.write("									<span class=\"fab fa-twitter\"></span>\r\n");
      out.write("								</a>\r\n");
      out.write("								<a href=\"#\" class=\"social-button facebook\">\r\n");
      out.write("									<span class=\"fab fa-facebook-f\"></span>\r\n");
      out.write("								</a>\r\n");
      out.write("								<a href=\"#\" class=\"social-button google\">\r\n");
      out.write("									<span class=\"fab fa-google-plus-g\"></span>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-sm-6 team-grids\">\r\n");
      out.write("					<div class=\"thumbnail team-agileits\">\r\n");
      out.write("						<img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/te3.jpg\" class=\"img-fluid\" alt=\"\" />\r\n");
      out.write("						<div class=\"effectd-caption\">\r\n");
      out.write("							<h4 class=\"mb-3\">Chunk Erson</h4>\r\n");
      out.write("							<div class=\"social-lsicon\">\r\n");
      out.write("								<a href=\"#\" class=\"social-button twitter\">\r\n");
      out.write("									<span class=\"fab fa-twitter\"></span>\r\n");
      out.write("								</a>\r\n");
      out.write("								<a href=\"#\" class=\"social-button facebook\">\r\n");
      out.write("									<span class=\"fab fa-facebook-f\"></span>\r\n");
      out.write("								</a>\r\n");
      out.write("								<a href=\"#\" class=\"social-button google\">\r\n");
      out.write("									<span class=\"fab fa-google-plus-g\"></span>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-sm-6 team-grids\">\r\n");
      out.write("					<div class=\"thumbnail team-agileits\">\r\n");
      out.write("						<img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/te4.jpg\" class=\"img-fluid\" alt=\"\" />\r\n");
      out.write("						<div class=\"effectd-caption\">\r\n");
      out.write("							<h4 class=\"mb-3\">Goes Marry</h4>\r\n");
      out.write("							<div class=\"social-lsicon\">\r\n");
      out.write("								<a href=\"#\" class=\"social-button twitter\">\r\n");
      out.write("									<span class=\"fab fa-twitter\"></span>\r\n");
      out.write("								</a>\r\n");
      out.write("								<a href=\"#\" class=\"social-button facebook\">\r\n");
      out.write("									<span class=\"fab fa-facebook-f\"></span>\r\n");
      out.write("								</a>\r\n");
      out.write("								<a href=\"#\" class=\"social-button google\">\r\n");
      out.write("									<span class=\"fab fa-google-plus-g\"></span>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- //about-team -->\r\n");
      out.write("\r\n");
      out.write("<!--footer-->\r\n");
      out.write("	<footer>\r\n");
      out.write("		<div class=\"container py-md-4 mt-md-3\">\r\n");
      out.write("			<div class=\"row footer-top-w3layouts-agile py-5\">\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-sm-6 footer-grid\">\r\n");
      out.write("					<div class=\"footer-title\">\r\n");
      out.write("						<h3>About Us</h3>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"footer-text\">\r\n");
      out.write("						<p>Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. lacinia eget consectetur sed, convallis at tellus..</p>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-sm-6 footer-grid\">\r\n");
      out.write("					<div class=\"footer-title\">\r\n");
      out.write("						<h3>Contact Us</h3>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"footer-office-hour\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"hd\">Address :</li>\r\n");
      out.write("							<li>No.27 - 5549436 street lorem, Newyork City, USA</li>\r\n");
      out.write("\r\n");
      out.write("						</ul>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"hd\">Phone:+ 1 (234) 567 8901</li>\r\n");
      out.write("							<li class=\"hd\">Email:\r\n");
      out.write("								<a href=\"mailto:info@example.com\">info@example.com</a>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li class=\"hd\">Fax: 1(234) 567 8901</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-sm-6 footer-grid\">\r\n");
      out.write("					<div class=\"footer-title\">\r\n");
      out.write("						<h3>Recent Posts</h3>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"footer-list\">\r\n");
      out.write("						<div class=\"flickr-grid\">\r\n");
      out.write("							<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\">\r\n");
      out.write("								<img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/g1.jpg\" class=\"img-fluid\" alt=\" \">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"flickr-grid\">\r\n");
      out.write("							<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\">\r\n");
      out.write("								<img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/g2.jpg\" class=\"img-fluid\" alt=\" \">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"flickr-grid\">\r\n");
      out.write("							<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\">\r\n");
      out.write("								<img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/g3.jpg\" class=\"img-fluid\" alt=\" \">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"flickr-grid\">\r\n");
      out.write("							<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\">\r\n");
      out.write("								<img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/g4.jpg\" class=\"img-fluid\" alt=\" \">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"flickr-grid\">\r\n");
      out.write("							<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\">\r\n");
      out.write("								<img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/g5.jpg\" class=\"img-fluid\" alt=\" \">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"flickr-grid\">\r\n");
      out.write("							<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\">\r\n");
      out.write("								<img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/g6.jpg\" class=\"img-fluid\" alt=\" \">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"flickr-grid\">\r\n");
      out.write("							<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\">\r\n");
      out.write("								<img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/g7.jpg\" class=\"img-fluid\" alt=\" \">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"flickr-grid\">\r\n");
      out.write("							<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\">\r\n");
      out.write("								<img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/g9.jpg\" class=\"img-fluid\" alt=\" \">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"flickr-grid\">\r\n");
      out.write("							<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\">\r\n");
      out.write("								<img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/g8.jpg\" class=\"img-fluid\" alt=\" \">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"clearfix\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-sm-6 footer-grid\">\r\n");
      out.write("					<div class=\"footer-title\">\r\n");
      out.write("						<h3>Subscribe</h3>\r\n");
      out.write("					</div>\r\n");
      out.write("					<p>Vivamus magna justo, lacinia eget consectetur sed.</p>\r\n");
      out.write("					<form action=\"#\" method=\"post\" class=\"newsletter\">\r\n");
      out.write("						<input class=\"email\" type=\"email\" placeholder=\"Your email...\" required=\"\">\r\n");
      out.write("						<button class=\"btn1\">\r\n");
      out.write("							<i class=\"far fa-envelope\"></i>\r\n");
      out.write("						</button>\r\n");
      out.write("					</form>\r\n");
      out.write("					<div class=\"clearfix\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!---->\r\n");
      out.write("	<div class=\"copyright py-3\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"copyrighttop\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li>\r\n");
      out.write("						<h4>Follow us on:</h4>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<a class=\"facebook\" href=\"#\">\r\n");
      out.write("							<i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("						</a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<a class=\"facebook\" href=\"#\">\r\n");
      out.write("							<i class=\"fab fa-twitter\"></i>\r\n");
      out.write("						</a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<a class=\"facebook\" href=\"#\">\r\n");
      out.write("							<i class=\"fab fa-google-plus-g\"></i>\r\n");
      out.write("						</a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<a class=\"facebook\" href=\"#\">\r\n");
      out.write("							<i class=\"fab fa-pinterest-p\"></i>\r\n");
      out.write("						</a>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"copyrightbottom\">\r\n");
      out.write("				<p>Â© 2018 Home Loan. All Rights Reserved | Design by\r\n");
      out.write("					<a href=\"http://w3layouts.com/\">W3layouts</a>\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"clearfix\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalCenterTitle\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">Home Loan</h4>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("		 <div class=\"agileits-w3layouts-info\">\r\n");
      out.write("			<img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/g6.jpg\" class=\"img-fluid\" alt=\"\" />\r\n");
      out.write("			<p>Duis venenatis, turpis eu bibendum porttitor, sapien quam ultricies tellus, ac rhoncus risus odio eget nunc. Pellentesque ac fermentum diam. Integer eu facilisis nunc, a iaculis felis. Pellentesque pellentesque tempor enim, in dapibus turpis porttitor quis. </p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-primary\">Save changes</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //Modal -->\r\n");
      out.write("<!-- js-->\r\n");
      out.write("	<script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/js/jquery-2.2.3.min.js\"></script>\r\n");
      out.write("<!-- js-->\r\n");
      out.write("	<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("	<script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/js/bootstrap.js \">\r\n");
      out.write("	</script>\r\n");
      out.write("	<!-- //Bootstrap Core JavaScript -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
