/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-01-16 07:16:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class homeLoanEMI_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Home Loan a Banking Category Flat Bootstrap Responsive\r\n");
      out.write("	Website Template | Services :: w3layouts</title>\r\n");
      out.write("<style>\r\n");
      out.write("/* Add your global styles here */\r\n");
      out.write("body {\r\n");
      out.write("	font-family: 'Poppins', sans-serif;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	background-color: #f5f5f5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header {\r\n");
      out.write("	background-color: #555;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	padding: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("	width: 80%;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add more styles as needed */\r\n");
      out.write("\r\n");
      out.write("/* Apply Online Section Styles */\r\n");
      out.write(".apply-online {\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	margin: 20px 0;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	box-shadow: 0 0 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".apply-online h2 span {\r\n");
      out.write("	color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".apply-online form {\r\n");
      out.write("	max-width: 600px;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".apply-online label {\r\n");
      out.write("	display: block;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".apply-online input[type=\"range\"] {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".apply-online button {\r\n");
      out.write("	background-color: #bfbfbf;\r\n");
      out.write("	color: #000;\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("/* Add more styles as needed */\r\n");
      out.write("\r\n");
      out.write("/* Result Section Styles */\r\n");
      out.write("#resultSection {\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".result-item {\r\n");
      out.write("	margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".result-item label {\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	width: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".result-item span {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	color: #333;\r\n");
      out.write("	font-weight: normal;\r\n");
      out.write("	margin-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add more styles as needed */\r\n");
      out.write("</style>\r\n");
      out.write("<!-- <style type=\"text/css\">\r\n");
      out.write("/* Global Styles */\r\n");
      out.write("body {\r\n");
      out.write("	font-family: 'Poppins', sans-serif;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	background-color: #f5f5f5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Header Styles */\r\n");
      out.write("/*   header {\r\n");
      out.write("        background-color: #333;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        padding: 10px 0;\r\n");
      out.write("    } */\r\n");
      out.write(".top {\r\n");
      out.write("	background-color: #555;\r\n");
      out.write("	padding: 5px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top-middle ul, .top-left ul {\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top-middle ul li, .top-left ul li {\r\n");
      out.write("	display: inline;\r\n");
      out.write("	margin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Apply Online Section Styles */\r\n");
      out.write(".apply-online {\r\n");
      out.write("	/* background-color: #fff; */\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	margin: 20px 0;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	box-shadow: 0 0 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".apply-online h2 span {\r\n");
      out.write("	color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".apply-online ul {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	padding: 60px;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".apply-online ul li {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin-right: 75px;\r\n");
      out.write("	vertical-align: top;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".apply-online ul li img {\r\n");
      out.write("	max-width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".apply-online ul li p {\r\n");
      out.write("	margin: 5px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".apply-online .apply-btn {\r\n");
      out.write("	background-color: #bfbfbf;\r\n");
      out.write("	color: #000;\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Footer Styles */\r\n");
      out.write("/*  footer {\r\n");
      out.write("        background-color: #f1f1f1;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        padding: 10px 0;\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("    } */\r\n");
      out.write("</style> -->\r\n");
      out.write("<!-- Additional stylesheets -->\r\n");
      out.write("<title>Home Loan a Banking Category Flat Bootstrap Responsive\r\n");
      out.write("	Website Template | Services :: w3layouts</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("	content=\"Home Loan Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("<script>\r\n");
      out.write("	addEventListener(\"load\", function() {\r\n");
      out.write("		setTimeout(hideURLbar, 0);\r\n");
      out.write("	}, false);\r\n");
      out.write("\r\n");
      out.write("	function hideURLbar() {\r\n");
      out.write("		window.scrollTo(0, 1);\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/bootstrap.css\"\r\n");
      out.write("	rel='stylesheet' type='text/css' />\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/style.css\"\r\n");
      out.write("	rel='stylesheet' type='text/css' />\r\n");
      out.write("<!-- font-awesome icons -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/fontawesome-all.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- //Custom Theme files -->\r\n");
      out.write("<!-- online fonts -->\r\n");
      out.write("<!-- titles -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"//fonts.googleapis.com/css?family=Raleway:300,400,500,600,700,800,900\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- body -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"//fonts.googleapis.com/css?family=Poppins:400,500,600,700,800\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("        // Function to update the display value for loan amount\r\n");
      out.write("        function updateLoanAmount() {\r\n");
      out.write("            var loanAmount = document.getElementById(\"loanAmount\");\r\n");
      out.write("            var loanAmountValue = document.getElementById(\"loanAmountValue\");\r\n");
      out.write("            loanAmountValue.textContent = loanAmount.value.replace(/\\B(?=(\\d{3})+(?!\\d))/g, \",\");\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Function to update the display value for interest rate\r\n");
      out.write("        function updateInterestRate() {\r\n");
      out.write("            var interestRate = document.getElementById(\"interestRate\");\r\n");
      out.write("            var interestRateValue = document.getElementById(\"interestRateValue\");\r\n");
      out.write("            interestRateValue.textContent = interestRate.value + \"%\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Function to update the display value for loan term\r\n");
      out.write("        function updateLoanTerm() {\r\n");
      out.write("            var loanTerm = document.getElementById(\"loanTerm\");\r\n");
      out.write("            var loanTermValue = document.getElementById(\"loanTermValue\");\r\n");
      out.write("            loanTermValue.textContent = loanTerm.value + \" years\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Function to calculate loan and update results\r\n");
      out.write("        function calculateLoan() {\r\n");
      out.write("            var loanAmount = parseFloat(document.getElementById(\"loanAmount\").value.replace(/,/g, ''));\r\n");
      out.write("            var interestRate = parseFloat(document.getElementById(\"interestRate\").value);\r\n");
      out.write("            var loanTerm = parseInt(document.getElementById(\"loanTerm\").value);\r\n");
      out.write("\r\n");
      out.write("            var monthlyRate = interestRate / 100 / 12;\r\n");
      out.write("    		var numberOfPayments = loanTerm * 12;\r\n");
      out.write("            var monthlyPayment = (loanAmount * monthlyRate) / (1 - Math.pow(1 + monthlyRate, -numberOfPayments));\r\n");
      out.write("\r\n");
      out.write("            document.getElementById(\"loanAmountResult\").innerHTML = \"Loan Amount: &#8377;\" + loanAmount.toLocaleString();\r\n");
      out.write("            document.getElementById(\"interestRateResult\").innerHTML = \"Interest Rate: \" + interestRate + \"%\";\r\n");
      out.write("            document.getElementById(\"loanTermResult\").innerHTML = \"Loan Term: \" + loanTerm + \" years\";\r\n");
      out.write("            document.getElementById(\"monthlyPaymentResult\").innerHTML = \"Monthly Payment: &#8377;\" + monthlyPayment.toFixed(2).toLocaleString();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Attach event listeners to range sliders\r\n");
      out.write("        document.getElementById(\"loanAmount\").addEventListener(\"input\", updateLoanAmount);\r\n");
      out.write("        document.getElementById(\"interestRate\").addEventListener(\"input\", updateInterestRate);\r\n");
      out.write("        document.getElementById(\"loanTerm\").addEventListener(\"input\", updateLoanTerm);\r\n");
      out.write("\r\n");
      out.write("        // Attach event listener to the Calculate button\r\n");
      out.write("        document.getElementById(\"calculateBtn\").addEventListener(\"click\", calculateLoan);\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- header -->\r\n");
      out.write("	<header>\r\n");
      out.write("		<div class=\"top\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"t-op row\">\r\n");
      out.write("					<div class=\"col-sm-6 top-middle\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a></li>\r\n");
      out.write("							<li><a href=\"#\"><i class=\"fab fa-twitter\"></i></a></li>\r\n");
      out.write("							<li><a href=\"#\"><i class=\"fab fa-google-plus-g\"></i></a></li>\r\n");
      out.write("							<li><a href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-sm-6 top-left\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><i class=\"fas fa-phone\"></i> +021 365 777</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("				<h1>\r\n");
      out.write("					<a class=\"navbar-brand text-capitalize\" href=\"index\"> Home Loan\r\n");
      out.write("					</a>\r\n");
      out.write("				</h1>\r\n");
      out.write("				<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("					data-target=\"#navbarSupportedContent\"\r\n");
      out.write("					aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("					aria-label=\"Toggle navigation\">\r\n");
      out.write("					<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("				</button>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("					<ul class=\"navbar-nav text-center  ml-lg-auto\">\r\n");
      out.write("						<li class=\"nav-item mr-3\"><a class=\"nav-link\" href=\"index\">Home\r\n");
      out.write("								<span class=\"sr-only\">(current)</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item  mr-3\"><a class=\"nav-link\" href=\"about\">About\r\n");
      out.write("								Us</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"nav-item dropdown mr-3\"><a\r\n");
      out.write("							class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("							role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("							aria-expanded=\"false\"> Services </a>\r\n");
      out.write("							<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"LoanApplyOnline\">Apply Online</a>\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"LoanApprovedProject\">Approved\r\n");
      out.write("									Project</a> <a class=\"dropdown-item\" href=\"LoanCalculator\">Loan\r\n");
      out.write("									Calculator</a>\r\n");
      out.write("							</div></li>\r\n");
      out.write("						<li class=\"nav-item dropdown mr-3\"><a\r\n");
      out.write("							class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("							role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("							aria-expanded=\"false\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </a>\r\n");
      out.write("							<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"UserProfile\">Profile</a> <a\r\n");
      out.write("									class=\"dropdown-item\" href=\"UserChangePassword\">Change\r\n");
      out.write("									Password</a> <a class=\"dropdown-item\" href=\"UserLogout\">Logout</a>\r\n");
      out.write("							</div></li>\r\n");
      out.write("						<!-- 	<li class=\"nav-item\">\r\n");
      out.write("							<a class=\"nav-link\" href=\"contact\">contact</a>\r\n");
      out.write("						</li> -->\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- //header -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Apply Online Section -->\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<form id=\"loanForm\"\r\n");
      out.write("			action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/HomeEMI\" method=\"post\"\r\n");
      out.write("			class=\"apply-online\">\r\n");
      out.write("			<h2 style=\"text-align: center\">\r\n");
      out.write("				<span>Loan Calculator</span>\r\n");
      out.write("			</h2>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"loanAmount\">Loan Amount: &#8377; <span\r\n");
      out.write("					id=\"loanAmountValue\">100,000</span></label> <input type=\"range\"\r\n");
      out.write("					id=\"loanAmount\" name=\"loanAmount\" min=\"10000\" max=\"10000000\"\r\n");
      out.write("					step=\"1000\" value=\"100000\">\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"interestRate\">Annual Interest Rate: <span\r\n");
      out.write("					id=\"interestRateValue\">5.0</span>\r\n");
      out.write("				</label> <input type=\"range\" id=\"interestRate\" name=\"interestRate\" min=\"1\"\r\n");
      out.write("					max=\"20\" step=\"0.1\" value=\"5.0\">\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"loanTerm\">Loan Term: <span id=\"loanTermValue\">15</span>\r\n");
      out.write("					\r\n");
      out.write("				</label> <input type=\"range\" id=\"loanTerm\" name=\"loanTerm\" min=\"1\" max=\"30\"\r\n");
      out.write("					step=\"1\" value=\"15\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"resultSection\" style=\"margin-top: 20px;\">\r\n");
      out.write("				<h2>Loan Calculation Results</h2>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"result-item\">\r\n");
      out.write("					<label>Loan Amount:  &#8377;</label> <span id=\"loanAmountResult\">100,000</span>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"result-item\">\r\n");
      out.write("					<label>Interest Rate:</label> <span id=\"interestRateResult\">5.0%</span>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"result-item\">\r\n");
      out.write("					<label>Loan Term:</label> <span id=\"loanTermResult\">15 years</span>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"result-item\">\r\n");
      out.write("					<label>Monthly Payment: &#8377;</label> <span id=\"monthlyPaymentResult\">0.00</span>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<button type=\"button\" id=\"calculateBtn\" onclick=\"calculateLoan()\">Calculate</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- <p>&nbsp;</p>\r\n");
      out.write("		<p>&nbsp;</p> -->\r\n");
      out.write("	<!-- <p class=\"txt-center\" style=\"text-align: center;\">\r\n");
      out.write("			<input type=\"submit\" class=\"apply-btn\" value=\"Apply Now\">\r\n");
      out.write("		</p> -->\r\n");
      out.write("	<!-- </div>\r\n");
      out.write("	</form> -->\r\n");
      out.write("	<!--footer-->\r\n");
      out.write("	<footer>\r\n");
      out.write("		<div class=\"container py-md-4 mt-md-3\">\r\n");
      out.write("			<div class=\"row footer-top-w3layouts-agile py-5\">\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-sm-6 footer-grid\">\r\n");
      out.write("					<div class=\"footer-title\">\r\n");
      out.write("						<h3>About Us</h3>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"footer-text\">\r\n");
      out.write("						<p>Curabitur non nulla sit amet nisl tempus convallis quis ac\r\n");
      out.write("							lectus. lacinia eget consectetur sed, convallis at tellus..</p>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-sm-6 footer-grid\">\r\n");
      out.write("					<div class=\"footer-title\">\r\n");
      out.write("						<h3>Contact Us</h3>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"footer-office-hour\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"hd\">Address :</li>\r\n");
      out.write("							<li>No.27 - 5549436 street lorem, Newyork City, USA</li>\r\n");
      out.write("\r\n");
      out.write("						</ul>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"hd\">Phone:+ 1 (234) 567 8901</li>\r\n");
      out.write("							<li class=\"hd\">Email: <a href=\"mailto:info@example.com\">info@example.com</a>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li class=\"hd\">Fax: 1(234) 567 8901</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-sm-6 footer-grid\">\r\n");
      out.write("					<div class=\"footer-title\">\r\n");
      out.write("						<h3>Recent Posts</h3>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"footer-list\">\r\n");
      out.write("						<div class=\"flickr-grid\">\r\n");
      out.write("							<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\"> <img\r\n");
      out.write("								src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/g1.jpg\"\r\n");
      out.write("								class=\"img-fluid\" alt=\" \">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"flickr-grid\">\r\n");
      out.write("							<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\"> <img\r\n");
      out.write("								src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/g2.jpg\"\r\n");
      out.write("								class=\"img-fluid\" alt=\" \">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"flickr-grid\">\r\n");
      out.write("							<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\"> <img\r\n");
      out.write("								src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/g3.jpg\"\r\n");
      out.write("								class=\"img-fluid\" alt=\" \">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"flickr-grid\">\r\n");
      out.write("							<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\"> <img\r\n");
      out.write("								src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/g4.jpg\"\r\n");
      out.write("								class=\"img-fluid\" alt=\" \">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"flickr-grid\">\r\n");
      out.write("							<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\"> <img\r\n");
      out.write("								src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/g5.jpg\"\r\n");
      out.write("								class=\"img-fluid\" alt=\" \">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"flickr-grid\">\r\n");
      out.write("							<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\"> <img\r\n");
      out.write("								src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/g6.jpg\"\r\n");
      out.write("								class=\"img-fluid\" alt=\" \">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"flickr-grid\">\r\n");
      out.write("							<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\"> <img\r\n");
      out.write("								src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/g7.jpg\"\r\n");
      out.write("								class=\"img-fluid\" alt=\" \">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"flickr-grid\">\r\n");
      out.write("							<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\"> <img\r\n");
      out.write("								src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/g9.jpg\"\r\n");
      out.write("								class=\"img-fluid\" alt=\" \">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"flickr-grid\">\r\n");
      out.write("							<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\"> <img\r\n");
      out.write("								src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/g8.jpg\"\r\n");
      out.write("								class=\"img-fluid\" alt=\" \">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"clearfix\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-sm-6 footer-grid\">\r\n");
      out.write("					<div class=\"footer-title\">\r\n");
      out.write("						<h3>Subscribe</h3>\r\n");
      out.write("					</div>\r\n");
      out.write("					<p>Vivamus magna justo, lacinia eget consectetur sed.</p>\r\n");
      out.write("					<form action=\"#\" method=\"post\" class=\"newsletter\">\r\n");
      out.write("						<input class=\"email\" type=\"email\" placeholder=\"Your email...\"\r\n");
      out.write("							required=\"\">\r\n");
      out.write("						<button class=\"btn1\">\r\n");
      out.write("							<i class=\"far fa-envelope\"></i>\r\n");
      out.write("						</button>\r\n");
      out.write("					</form>\r\n");
      out.write("					<div class=\"clearfix\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!---->\r\n");
      out.write("	<div class=\"copyright py-3\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"copyrighttop\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li>\r\n");
      out.write("						<h4>Follow us on:</h4>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li><a class=\"facebook\" href=\"#\"> <i\r\n");
      out.write("							class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<li><a class=\"facebook\" href=\"#\"> <i\r\n");
      out.write("							class=\"fab fa-twitter\"></i>\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<li><a class=\"facebook\" href=\"#\"> <i\r\n");
      out.write("							class=\"fab fa-google-plus-g\"></i>\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<li><a class=\"facebook\" href=\"#\"> <i\r\n");
      out.write("							class=\"fab fa-pinterest-p\"></i>\r\n");
      out.write("					</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"copyrightbottom\">\r\n");
      out.write("				<p>\r\n");
      out.write("					Â© 2018 Home Loan. All Rights Reserved | Design by <a\r\n");
      out.write("						href=\"http://w3layouts.com/\">W3layouts</a>\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"clearfix\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Modal -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("		aria-labelledby=\"exampleModalCenterTitle\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h4 class=\"modal-title\">Home Loan</h4>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<div class=\"agileits-w3layouts-info\">\r\n");
      out.write("						<img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/g6.jpg\"\r\n");
      out.write("							class=\"img-fluid\" alt=\"\" />\r\n");
      out.write("						<p>Duis venenatis, turpis eu bibendum porttitor, sapien quam\r\n");
      out.write("							ultricies tellus, ac rhoncus risus odio eget nunc. Pellentesque\r\n");
      out.write("							ac fermentum diam. Integer eu facilisis nunc, a iaculis felis.\r\n");
      out.write("							Pellentesque pellentesque tempor enim, in dapibus turpis\r\n");
      out.write("							porttitor quis.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("						data-dismiss=\"modal\">Close</button>\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-primary\">Save changes</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- //Modal -->\r\n");
      out.write("	<!-- js-->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery-2.2.3.min.js\"></script>\r\n");
      out.write("	<!-- js-->\r\n");
      out.write("	<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/bootstrap.js \">\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("	<!-- //Bootstrap Core JavaScript -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
